title: Mariz Portfolio
description: A curious and resourceful software engineer with a strong passion for creating a positive impact through disruptive technologies.
theme: jekyll-theme-cayman # You can choose any theme
